Makeup2.Web/Controllers/GamasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Makeup2.Web.Models;

namespace Makeup2.Web.Controllers
{
    [Authorize]
    public class GamasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Gamas
        public ActionResult Index()
        {
            return View(db.Gamas.ToList());
        }

        // GET: Gamas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gama gama = db.Gamas.Include(a => a.Maquillajes).Where( a => a.Id==id).SingleOrDefault();
            if (gama == null)
            {
                return HttpNotFound();
            }
            return View(gama);
        }

        // GET: Gamas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Gamas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Tipo")] Gama gama)
        {
            if (ModelState.IsValid)
            {
                db.Gamas.Add(gama);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gama);
        }

        // GET: Gamas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gama gama = db.Gamas.Find(id);
            if (gama == null)
            {
                return HttpNotFound();
            }
            return View(gama);
        }

        // POST: Gamas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Tipo")] Gama gama)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gama).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gama);
        }

        // GET: Gamas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gama gama = db.Gamas.Find(id);
            if (gama == null)
            {
                return HttpNotFound();
            }
            return View(gama);
        }

        // POST: Gamas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gama gama = db.Gamas.Find(id);
            db.Gamas.Remove(gama);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Makeup2.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Makeup2.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Makeup2.Web/Controllers/RolesController.cs
using Makeup2.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Makeup2.Web.Controllers
{

    public class RolesController : Controller
    {
        readonly ApplicationDbContext db = new ApplicationDbContext();
        // GET: Roles
        public ActionResult Index()
        {
            var users = db.Users.ToList();
            return View(users);
        }
        public ActionResult AddRoles(string id)
        {
            var user = db.Users.Find(id);
            return View();
        }
    }
}

Makeup2.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<body class="bg-principal">
<p class="pt-5">
<p class="pt-5">
    <h1 class="text-center"><img src="~/Content/Img/Logo.png" width="200" height="150"/>   MakeUp Forever</h1>

<p class="text-center">Esta es una pagina para la compra de maquillaje<br />
    Aqui podras encontrar alguno de tus productos favoritos<br />
    Los que mas estan de moda y los mejores del mercado</p>
    </body>

Makeup2.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<p class="pt-5">
<p class="pt-5">
    <h2 class="text-center">Contactanos</h2>


    <address class="text-center">
        ¡Bienvenidx, estamos listos para ayudarte!<br />
        Por favor contáctanos a través nuestro correo guadalupe.castillo17@tectijuana.edu.mx
    </address>

    <address class="text-center">
        <a href="https://www.facebook.com/Nyxcosmeticsmx/" title="Facebook"><img src="~/Content/Img/ficono.png" width="25" height="25"/></a>
        <a href="https://twitter.com/NYXcosmeticsMX?lang=es" title="Twitter"><img src="~/Content/Img/ticono.png" width="25" height="25" /></a>
        <a href="https://www.instagram.com/nyxcosmetics_mx/" title="Instagram"><img src="~/Content/Img/iicono.png" width="25" height="25" /></a>
    </address>

Makeup2.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Inicio";
 
}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Makeup Forever</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/styles.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-principal fixed-top">
        <div class="container bg-prinks">
            <a class="navbar-brand" href=""><img src="~/Content/Img/Logo.png" width="100" height="75" />@Html.ActionLink("MakeUp Forever", "Index", "Home", null, new { @class = "nav-link" })</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                   

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item  text-black"><a href="@Url.Action("Index","Gamas")" class="nav-link  text-black">Marcas</a></li>
                        <li class="nav-item  text-black"><a href="@Url.Action("Index","MAquillajes")" class="nav-link  text-black">Las mas destacado</a></li>
                    }
                    @if (User.IsInRole("Administrator"))
                    {
                        <li class="nav-item  text-black"><a href="@Url.Action("Index","Roles")" class="nav-link  text-black">Roles</a></li>
                    }


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
       
    </nav>

        <!-- Page Content -->
        <div class="container p-2">

            <div class="row">

                    <div class="col-lg-3 p">
                <p class="pt-5">
                <p class="pt-5">
                    <h1>Cosmeticos</h1>
                    <ul>
                    <li class="nav-item"><a href="@Url.Action("Index","Home/About")" class="nav-link">Acerca de</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","Home/Contact")" class="nav-link">Contactanos</a></li>
                        </ul>
</div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1" class="active"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="~/Content/Img/carrito.jpg" width="800" height="300" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="~/Content/Img/neom.jpg" width="800" height="400" alt="Second slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="@Url.Action("Index","Compras/PaletaJames")" class="nav-link"><img class="card-img-top" src="~/Content/Img/paletacharles.jpg" width="700" height="400" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="@Url.Action("Index","Compras/PaletaJames")" class="nav-link">Paleta James Charles</a>
                            </h4>
                            <h5>$980.99</h5>
    <p class="card-text">MORPHE X JAMES CHARLES LA MINI PALETA</p>
    </div>
    <div class="card-footer">
        <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
    </div>
    </div>
    </div>

    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
            <a href="@Url.Action("Index","Compras/LabialJeffree")"><img class="card-img-top" src="~/Content/Img/labialjeffree.jpg" width="700" height="400" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="@Url.Action("Index","Compras/LabialJeffree")">Labiales Jeffree Star</a>
                </h4>
                <h5>$1200.00</h5>
                <p class="card-text">Morphe x Jeffree Star Iconic Nudes Lip Collection – Juego de 5 piezas</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
            </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
            <a href="@Url.Action("Index","Compras/BrochaChanel")"><img class="card-img-top" src="~/Content/Img/brochaschanel.jpg" width="700" height="400" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="@Url.Action("Index","Compras/BrochaChanel")">Brochas Chanel</a>
                </h4>
                <h5>$1900.00</h5>
                <p class="card-text">Juego de brochas de maquillaje (10 unidades, color negro, bolsa de piel.</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
            </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
            <a href="@Url.Action("Index","Compras/IluminadorTarte")"><img class="card-img-top" src="~/Content/Img/iluminadortarte.jpg" width="700" height="400" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="@Url.Action("Index","Compras/IluminadorTarte")">Iluminador Tarte</a>
                </h4>
                <h5>$560.00</h5>
                <p class="card-text">Tarte Clay 12 horas resaltador # Sparkler - Acabado radiante</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
            </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
            <a href="@Url.Action("Index","Compras/PestaniasKara")"><img class="card-img-top" src="~/Content/Img/pestaniaskara.jpg" width="700" height="400" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="@Url.Action("Index","Compras/PestaniasKara")">Pestañas Kara Beauty</a>
                </h4>
                <h5>$200.00</h5>
                <p class="card-text">Extensiones de pestañas individuales naturales KARA BEAUTY, 12 unidades, pestañas postizas brillantes de 5.5 pulgadas largo para ojos, color negro, atadas, 12mm, Negro</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
            </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
            <a href="@Url.Action("Index","Compras/MacBase")"><img class="card-img-top" src="~/Content/Img/macbase.jpg" width="700" height="400" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="@Url.Action("Index","Compras/MacBase")">Mac Base</a>
                </h4>
                <h5>$900.00</h5>
                <p class="card-text">Mac Studio WaterWeight SPF 30 NC15 de la base por M.A.C</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
            </div>
        </div>
    </div>

    </div>
    <!-- /.row -->
    </div>
    <!-- /.col-lg-9 -->
    </div>
    <!-- /.row -->
    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-principal">
        <div class="container">
            <p class="m-0 text-center text-black">Cosmeticos &copy; 2020</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="~/Scripts/scripts.js"></script>

</body>

</html>